

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-clinica
    env_file:
      # - ./backend/.env
      - .env.docker
    ports:
      - "1433:1433"
    volumes:
      - sql_data_clinica:/var/opt/mssql
    restart: always

volumes:
  sql_data_clinica:
    # driver: local