services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-clinica
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sql_data_clinica:/var/opt/mssql
    restart: always
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P $SA_PASSWORD -C -Q 'SELECT 1' || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 180s

  backend:
    build: ./backend
    container_name: backend-clinica
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/node_modules/.prisma
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: dev  
    container_name: frontend-clinica
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/Expedientes_Clinicos:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  sql_data_clinica: